version: "3.3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "9000:9000"
    volumes:
      - ./api:/app
